apiVersion: v1
kind: Namespace
metadata:
  name: vpn
---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-set
  namespace: vpn
type: Opaque
data:
  wg0.conf.template: W0ludGVyZmFjZV0KQWRkcmVzcyA9IDE3Mi4xNi4xNi4wLzIwCkxpc3RlblBvcnQgPSA1MTgyMApQcml2YXRlS2V5ID0gV09vZlV0TVJzRFZ1Lzl5b05FNlVBTUNZZTJQeVM5U0VsK0xJVERUYjBIdz0KUG9zdFVwID0gaXB0YWJsZXMgLUEgRk9SV0FSRCAtaSB3ZzAgLWogQUNDRVBUOyBpcHRhYmxlcyAtdCBuYXQgLUEgUE9TVFJPVVRJTkcgLW8gZXRoMCAtaiBNQVNRVUVSQURFClBvc3RVcCA9IHN5c2N0bCAtdyAtcSBuZXQuaXB2NC5pcF9mb3J3YXJkPTEKUG9zdERvd24gPSBpcHRhYmxlcyAtRCBGT1JXQVJEIC1pIHdnMCAtaiBBQ0NFUFQ7IGlwdGFibGVzIC10IG5hdCAtRCBQT1NUUk9VVElORyAtbyBldGgwIC1qIE1BU1FVRVJBREUKUG9zdERvd24gPSBzeXNjdGwgLXcgLXEgbmV0LmlwdjQuaXBfZm9yd2FyZD0wCgojYmFzZTEKW1BlZXJdClB1YmxpY0tleSA9IGNpVUN2cDIwVGxxcjcyZXc4b0gydHJOR04rWmJMazcrZ1VoUTdDMkRKR2s9CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuMi8zMgojYmFzZTIKW1BlZXJdClB1YmxpY0tleSA9IDB1Mi9pZytqSzFSSTFlRkoxbXpVcHZ1RE1lMWVZZnJNL1BEWHNvYkszWG89CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuMy8zMgojemFyawpbUGVlcl0KUHVibGljS2V5ID0gOGxlazVBUDdvNGxsa3BvYVpnZzUyb3kvMi85Tkp1TlpDTm15MGlVbWdtYz0KQWxsb3dlZElQcyA9IDE3Mi4xNi4xNi41LzMyCiNqdWxpYW4KW1BlZXJdClB1YmxpY0tleSA9IFdRZFB4bk9OZ0tDU1VhRlRRVWwyaEJSRXA0elFRVENVdGJBOFpEZHlTVlk9CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuNi8zMgojc3RldmVuenoKW1BlZXJdClB1YmxpY0tleSA9IHByM0ViZjVUY0Zrc0sySjJyVFJFckFuVjM2VFR2SVBZV3pla2wwV0xQREk9CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuNy8zMgojankKW1BlZXJdClB1YmxpY0tleSA9IEJ3VzRqRmtROEk2MW1XcmtSc291bFdoZ3V4VU1JMXQ2T3Vwc3RHc0FtbU09CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuOC8zMgojamFzZW4KW1BlZXJdClB1YmxpY0tleSA9IGFPd3A3M2t6NjdWSHpieXFzcC85Wk8zYit6WUgwRStENXFDSkd2NFhYbUE9CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuOS8zMgojYnJ1Y2UKW1BlZXJdClB1YmxpY0tleSA9IHRJdEdFUW1naFd3cjgyeGNXbWxWOVV5eEJhc0N0RlBZamVzTWpkOEtpWGs9CkFsbG93ZWRJUHMgPSAxNzIuMTYuMTYuMTAvMzI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    meta.helm.sh/release-name: wireguard
  labels:
  name: wireguard
  namespace: vpn
spec:
  selector:
    matchLabels:
      app: wireguard
  replicas: 0
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: "wireguard"
        image: "linuxserver/wireguard:latest"
        ports:
          - containerPort: 51820
        env:
          - name: "TZ"
            value: "Asia/Taipei"
          - name: "SERVERPORT"
            value: "51820"
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
        volumeMounts:
        - mountPath: /etc/wireguard/wg0.conf
          subPath: wg0.conf.template
          name: wireguard-config
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE      
      volumes:
      - name: wireguard-config
        secret:
          secretName: wireguard-set
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-svc
  namespace: vpn
spec:
  type: LoadBalancer
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820