apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc-router
  namespace: token-api
  labels:
    ingress: router       #标签
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/location-snippets: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $http_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
spec:
  rules:
  - host: "prodtoken.gttest13.com"
    http:
      paths:
      - path: /(metatoken/|token/|mmerchant/|mtoken/|blockchain/|merchant/|order/)
        pathType: Prefix
        backend:
          service:
            name: trade-svc
            port:
              number: 10001
      - path: /(user/|mgruser/)
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 10001      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: token-ui-svc
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-svc
  namespace: token-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  labels:
    ingress: router       #标签