##Deployment部署文件
apiVersion: apps/v1     #接口版本
kind: Deployment        #接口类型
metadata:   
  name: confirm-worker        #depolymet名称
  namespace: token-api    #命名空间
  labels:
    app: confirm-worker       #标签
spec:
  selector:
    matchLabels:
      app: confirm-worker
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0     #更新时候最大无效pod数量
      maxSurge: 1           #更新时候每次最多增加pod数量
  template:
    metadata:
      labels:
        app: confirm-worker       #模板名称必填
    spec:                   #定义容器模板，该模板可以包含多个容器
      containers:
      - name: confirm-worker      #镜像名称
        #resources:          ##CPU内存限制
        #  limits:
        #    cpu: 500m
        #    memory: 600Mi
        #  requests:
        #    cpu: 250m
        #    memory: 300Mi
        image: gcr.io/rd-test-64435/token_worker_svc:v23.6.8.1  #镜像地址        #如果command和args均没有写，那么用Docker默认的配置。
        #如果command写了，但args没有写，那么Docker默认的配置会被忽略而且仅仅执行.yaml文件的command（不带任何参数的）。
        #如果command没写，但args写了，那么Docker默认配置的ENTRYPOINT的命令行会被执行，但是调用的参数是.yaml中的args。
        #如果如果command和args都写了，那么Docker默认的配置被忽略，使用.yaml的配置。
        imagePullPolicy: IfNotPresent  #如果不存在则拉取
        ports:           
        - containerPort: 10001    #对service暴露端口
        - containerPort: 9000 
        livenessProbe:   #表示container是否处于live状态。如果LivenessProbe失败，LivenessProbe将会通知kubelet对应的container不健康了。
                         #随后kubelet将kill掉container，并根据RestarPolicy进行进一步的操作。默认情况下LivenessProbe在第一次检测之前初始化值为Success，
                         #如果container没有提供LivenessProbe，则也认为是Success；
          httpGet:
            path: /hc    #如果没有心跳检测接口就为/
            scheme: HTTP
            port: 10001
          initialDelaySeconds: 180   ##启动后延时多久开始运行检测
          periodSeconds: 120
          timeoutSeconds: 5
        env:        ##通过环境变量的方式，直接传递pod=自定义Linux OS环境变量
        - name: "SYS_MODULE" #局策略可使用configMap的配置Key，
          value: "User"
        args: ["ASPNETCORE_ENVIRONMENT=Kubernetes", "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0"]
        volumeMounts:   #挂载volumes中定义的磁盘
        - name: secrets
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: secrets
        secret:
          secretName: confirm-worker-settings           #配置文件名称
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: cash-api
#   namespace: token-api
# spec:
#   maxReplicas: 10
#   minReplicas: 1
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: cash-api
#   targetCPUUtilizationPercentage: 95
---
#定义对外访问的服务名字和端口
apiVersion: v1
kind: Service
metadata:
  name: user-svc            #服务名字
  namespace: token-api         #命名空间
spec:
  selector:
    app: confirm-worker           #        
  type: NodePort
  ports:
  - protocol: TCP   
    port: 10001  
    targetPort: 10001
    name: userapi
  - protocol: TCP   
    port: 9000  
    targetPort: 9000
    name: newthrift
