apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-config
  namespace: swjapi
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-config
  namespace: kube-system
spec:
  timeoutSec: 1800   #超时设定，如果不设定socket会每30秒断开一次
  connectionDraining:
    drainingTimeoutSec: 1800