apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: swjapi
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3.8-management"
          imagePullPolicy: IfNotPresent
          env:
          - name: "RABBITMQ_DEFAULT_VHOST"
            value: "/"
          - name: "RABBITMQ_DEFAULT_USER"
            value: "admin"
          - name: "RABBITMQ_DEFAULT_PASS"
            value: "aa1234"
          - name: "TZ"
            value: "Asia/Shanghai"
          volumeMounts:
          - name: persisitent-storage-rabbitmq
            mountPath: /var/lib/rabbitmq
          ports:
            - name: rabbitmq-web
              containerPort: 15672
              protocol: TCP
            - name: rabbitmq-admin
              containerPort: 5672
              protocol: TCP
          livenessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
      volumes:
      - name: persisitent-storage-rabbitmq
        hostPath:
          path: /var/data/rabbitmq
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc       
  namespace: swjapi       
spec:
  selector:
    app: rabbitmq       
  type: NodePort
  ports:
  - protocol: TCP   
    port: 15672  
    targetPort: 15672
    name: rabbitmq-web
  - protocol: TCP   
    port: 5672  
    targetPort: 5672
    name: rabbitmq-server