apiVersion: apps/v1
kind: Deployment
metadata:
  name: agile-conf
  namespace: edapi
  labels:
    app: agile-conf
spec:
  selector:
    matchLabels:
      app: agile-conf
  replicas: 1
  template:
    metadata:
      labels:
        app: agile-conf
    spec:
      containers:
        - name: agile-conf
          image: "kklldog/agile_config:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: "TZ"
              value: "Asia/Shanghai"
            - name: "adminConsole"
              value: "true"
            - name: "db__provider"
              value: "sqlserver"
            - name: "db__conn"
              valueFrom:
                secretKeyRef:
                  name: agile-conn
                  key: config_json
          ports:
          - containerPort: 5000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 250m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: agile-svc
  namespace: edapi
spec:
  selector:
    app: agile-conf
  type: ClusterIP
  ports:
  - protocol: TCP   
    port: 5000  
    targetPort: 5000
    name: ui