apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ed-router
  namespace: edapi
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/location-snippets: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $http_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
spec:
  rules:
  - host: "edco.cdweinet.com"
    http:
      paths:
      - path: /activities/
        pathType: Prefix
        backend:
          service:
            name: activies-svc
            port:
              number: 10001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edco-ui-svc
            port:
              number: 8080
