apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ed-router
  namespace: edapi
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/location-snippets: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $http_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
spec:
  rules:
  - host: "api.cdweinet.com"
    http:
      paths:
      # - path: /activities/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: activies-svc
      #       port:
      #         number: 10001
      # - path: /callcenter/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: callcenter-svc
      #       port:
      #         number: 10001
      # - path: /cash/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: cash-svc
      #       port:
      #         number: 10001
      # - path: /credit/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: credit-svc
      #       port:
      #         number: 10001
      # - path: /maintain/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: maintain-svc
      #       port:
      #         number: 10001
      # - path: /message/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: msg-svc
      #       port:
      #         number: 10001
      # - path: /paychange/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: paychange-svc
      #       port:
      #         number: 10001
      # - path: /product/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: product-svc
      #       port:
      #         number: 10001
      # - path: /system/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: system-svc
      #       port:
      #         number: 10001
      #- path: /user/
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 10001
      # - path: /warning/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: warning-svc
      #       port:
      #         number: 10001
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: warning-svc
      #       port:
      #         number: 10001
  - host: "edco.cdweinet.com"
    http:
      paths:
      - path: /hangfire/
        pathType: Prefix
        backend:
          service:
            name: backgroundtasks-svc
            port:
              number: 10001
      - path: /callcenter/
        pathType: Prefix
        backend:
          service:
            name: callcenter-svc
            port:
              number: 10001
      - path: /srdemo/
        pathType: Prefix
        backend:
          service:
            name: edco-ui-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transit-svc
            port:
              number: 10001
  # - host: "agapi.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /activities/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: activies-svc
  #           port:
  #             number: 10001
  #     - path: /message/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: msg-svc
  #           port:
  #             number: 10001
  #     - path: /product/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: product-svc
  #           port:
  #             number: 10001
  #     - path: /system/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: system-svc
  #           port:
  #             number: 10001
  #     - path: /user/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: user-svc
  #           port:
  #             number: 10001
  # - host: "edag.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: edco-ui-svc
  #           port:
  #             number: 8080 
  # - host: "seq.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: seq-svc
  #           port:
  #             number: 5342

