apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ed-router
  namespace: edapi
  labels:
    ingress: router       #标签
  annotations:
    cloud.google.com/neg: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
        }
spec:
  rules:
  # - host: "api.cdweinet.com"
  #   http:
  #     paths:
      # - path: /activities/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: activies-svc
      #       port:
      #         number: 10001
      # - path: /callcenter/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: callcenter-svc
      #       port:
      #         number: 10001
      # - path: /cash/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: cash-svc
      #       port:
      #         number: 10001
      # - path: /credit/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: credit-svc
      #       port:
      #         number: 10001
      # - path: /maintain/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: maintain-svc
      #       port:
      #         number: 10001
      # - path: /message/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: msg-svc
      #       port:
      #         number: 10001
      # - path: /paychange/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: paychange-svc
      #       port:
      #         number: 10001
      # - path: /product/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: product-svc
      #       port:
      #         number: 10001
      # - path: /system/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: system-svc
      #       port:
      #         number: 10001
      #- path: /user/
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: user-svc
      #       port:
      #         number: 10001
      # - path: /warning/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: warning-svc
      #       port:
      #         number: 10001
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: warning-svc
      #       port:
      #         number: 10001
  - host: "edco.cdweinet.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edco-ui-svc
            port:
              number: 8080
  # - host: "agapi.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /activities/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: activies-svc
  #           port:
  #             number: 10001
  #     - path: /message/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: msg-svc
  #           port:
  #             number: 10001
  #     - path: /product/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: product-svc
  #           port:
  #             number: 10001
  #     - path: /system/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: system-svc
  #           port:
  #             number: 10001
  #     - path: /user/
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: user-svc
  #           port:
  #             number: 10001
  # - host: "edag.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: edco-ui-svc
  #           port:
  #             number: 8080 
  # - host: "seq.cdweinet.com"
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: seq-svc
  #           port:
  #             number: 5342

