apiVersion: v1
kind: Endpoints
metadata:
  name: otc-cloudsql-svc
  namespace: otcapi
subsets:
  - addresses:
      - ip: 34.87.46.208
    ports:
      - port: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: otc-cloudsql-svc
  namespace: otcapi
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
