apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edco-swj-ingress
  namespace: api-swj
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - agile.gttest13.com
    secretName: swj-agile-tls
  - hosts:
    - gke.gttest13.com
    secretName: swj-gke-tls 
  # Set domain
  rules:
  - host: agile.gttest13.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agile-svc
            port:
              number: 5000
  - host: gke.gttest13.com
    http:
      paths:
      - path: /activies/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: activies-svc
            port:
              number: 10001
      - path: /callcenter/
        pathType: Prefix
        backend:
          service:
            name: callcenter-svc
            port:
              number: 10001
      - path: /maintain/
        pathType: Prefix
        backend:
          service:
            name: maintain-svc
            port:
              number: 10001
      - path: /cash/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: cash-svc
            port:
              number: 10001
      - path: /credit/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: credit-svc
            port:
              number: 10001
      - path: /message/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: msg-svc
            port:
              number: 10001
      - path: /product/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: product-svc
            port:
              number: 10001
      - path: /report/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: report-svc
            port:
              number: 10001
      - path: /site/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: site-svc
            port:
              number: 10001
      - path: /statistics/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: statistics-svc
            port:
              number: 10001
      - path: /system/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: system-svc
            port:
              number: 10001
      - path: /user/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 10001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edco-swj-svc
            port:
              number: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: swj-agile-tls
  namespace: api-swj
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUcxVENDQkwyZ0F3SUJBZ0lRYkZXcjI5QUhrc2VkQnd6WUVaN1d2ekFOQmdrcWhraUc5dzBCQVF3RkFEQ0IKaURFTE1Ba0dBMVVFQmhNQ1ZWTXhFekFSQmdOVkJBZ1RDazVsZHlCS1pYSnpaWGt4RkRBU0JnTlZCQWNUQzBwbApjbk5sZVNCRGFYUjVNUjR3SEFZRFZRUUtFeFZVYUdVZ1ZWTkZVbFJTVlZOVUlFNWxkSGR2Y21zeExqQXNCZ05WCkJBTVRKVlZUUlZKVWNuVnpkQ0JTVTBFZ1EyVnlkR2xtYVdOaGRHbHZiaUJCZFhSb2IzSnBkSGt3SGhjTk1qQXcKTVRNd01EQXdNREF3V2hjTk16QXdNVEk1TWpNMU9UVTVXakJMTVFzd0NRWURWUVFHRXdKQlZERVFNQTRHQTFVRQpDaE1IV21WeWIxTlRUREVxTUNnR0ExVUVBeE1oV21WeWIxTlRUQ0JTVTBFZ1JHOXRZV2x1SUZObFkzVnlaU0JUCmFYUmxJRU5CTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFobWx6ZnFPMU1kZ2oKNFczZHBCUFRWQlgxQXV2Y0F5RzFmbDBkVW53L01ldWVDV3pSV1RoZVozNUxWbzkxa0xJM0REVmFaS1crVEJBcwpKQmpFYlltTXdjV1NUV1lDZzUzMzRTRjArY3REQXNGeHNYK3JURGg5a1NyRy80bXA2T1NodWJMYUVJVUppWm80CnQ4NzNUdVNkMFdqNURXdDNEdHBBRzhUMzVsL3YreHJOOHViOFBTU29YNVZrZ3craldmNEtRdE52VUZMRHE4bUYKV2hVblBMNmpIQUFEWHB2czRsVE5Zd090eDl5UXRicHh3U3Q3UUpZMStJQ3JtUkpCNkJ1S1J0L2pmREpGOUpzYwpSUVZsSEl4UWRLQUpsN29hVm5YZ0RrcXRrMnFkZGQza0NEWGQ3NGd2ODEzRzkxejdDanNHeUo5M29KSWxOUzNVCmdGYkQ2VjU0Sk1nWjNyU21vdFliejk4b1p4WDdNS2J0Q20xYUovcStoVHYyWUsxeU14cm5mY2llS21PWUJiRkQKaG5XNU82Uk1BNzAzZEJLOTJqNlhSTjJFdHRMa1F1dWpaZ3kralhSS3RhV01JbGtOa1dKbU9pSG1FclFuZ0h2dAppTmtJY2pKdW1xMWRkRlg0aWFUSTQwYTZ6Z3ZJQnR4RmVEczJSZmNhSDczZXI3Y3ROVVVxZ1FUNXJGZ0poTW1GCng3NnJRZ0I1T1pVa29kYjVrMmV4N1ArR3U0Sjg2YlMxNTA5NFV1WWNWMDloVmVrbm1UaDVFeDlDQktpcExTMlcKMndLQmFrZithVlluTkNVNlMwbkFTcXQyeHJacEdDMXY3djZEaHVlcHl5SnRuM3FTVjJQb0JpVTVTcWwrYUFScAp3VWliUU1HbTQ0Z2p5TkRxRGxWcCtTaExRbFVIOXg4Q0F3RUFBYU9DQVhVd2dnRnhNQjhHQTFVZEl3UVlNQmFBCkZGTjV2MXFxSzByUFZJRGgySnZBbmZLeUEyYkxNQjBHQTFVZERnUVdCQlRJMlhob290a1phTlU5Y3Q1ZkNqN2MKdFlhR3BqQU9CZ05WSFE4QkFmOEVCQU1DQVlZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0lnWURWUjBnQkJzd0dUQU5CZ3NyQmdFRUFiSXhBUUlDClRqQUlCZ1puZ1F3QkFnRXdVQVlEVlIwZkJFa3dSekJGb0VPZ1FZWS9hSFIwY0RvdkwyTnliQzUxYzJWeWRISjEKYzNRdVkyOXRMMVZUUlZKVWNuVnpkRkpUUVVObGNuUnBabWxqWVhScGIyNUJkWFJvYjNKcGRIa3VZM0pzTUhZRwpDQ3NHQVFVRkJ3RUJCR293YURBL0JnZ3JCZ0VGQlFjd0FvWXphSFIwY0RvdkwyTnlkQzUxYzJWeWRISjFjM1F1ClkyOXRMMVZUUlZKVWNuVnpkRkpUUVVGa1pGUnlkWE4wUTBFdVkzSjBNQ1VHQ0NzR0FRVUZCekFCaGhsb2RIUncKT2k4dmIyTnpjQzUxYzJWeWRISjFjM1F1WTI5dE1BMEdDU3FHU0liM0RRRUJEQVVBQTRJQ0FRQVZEd29JelFEVgplcmNUMGVZcVpqQk5KOFZOV3dWRmxRT3RaRVJxbjVpV25FVmFMWlpkenhsYnZ6MkZ4MEV4VU51VUVnWWtJVk00CllvY0trQ1E3aE81bm9pY29xL0RyRVlINUl1TmN1VzFJOEpKWjlETHVCMWZZdklIbFoySkc0NmlOYlZLQTN5Z0EKRXo4NlJ2RFFsdDJDNDk0cXFQVkl0UmpyejlZbEpFR1QwRHJ0dHlBcHEwWUxGRHpmK1oxcGtNaGg3Yys3ZlhlSgpxbUloZkpwZHVLYzhIRVFrWVFRU2hlbjQyNlMzSDBKcklBYktjQkNpeVlGdU9oZnl2dXdWQ0ZEZkZ2cmpBRGpkCjRqWDF1UVhkMTYxSXlGUmJtODlzMk9qNW9VMXdEWXo1c3graG9DdWg2bFNzKy91UHVXb21JcTN5MUdERk5hZlcKK0xzSEJVMTZsUW81UTJ5aDI1bGFRc0tSZ3lQbU1wSEo5OGVkbTZ5MnNIVWFiQVNtUkh4dkdpdXd3RTI1YURVMAoyU0FlZXB5SW1KMkN6QjgwWUc3V3hseW5IcU5ocEU3eGZDN1B6UWxMZ21mRUhkVSt0SEZlUWF6UlFuckZrVzJXCmtxUkdJcTdjS1JueXlwdmpQTWtqZWlWOWxSZEFNOWZTSnZzQjNzdlV1dTFjb0lHMXh4STF5ZWdvR000cjVRUDQKUkdJVnZZYWlJNzZDMGRqb1NiUS9ka0lVVVhRdUI4QUw1anlIMzRnM0JaYWFYeXZwbW5WNGlscHBNWFZBbkFZRwpPTjUxV2hKNlcweE5kTkp3ellBU1pZSCt0bUNXSStONjBHdjJOTk1HSHdNWjdlOWJYZ3pVQ1pINUZhQkZER1I1ClM5VldxSEI3M1ErT3lJVnZJYktZY1NjMncvYVN1RktHU0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBaWVwVHVieUpUMGRoVXlFbUV2cHBqcWh3bjVGS1E5NHM3dmdsclJ5M0JnWUdEalplCmVYVit1VDZSb1k2a1UvWnhDWkhmRnZubnBVR3hDM3BlYzNrNi8xbUdiZkZkS1ppSlRENitIMFFEU3BXdFRuTTMKWHhuc21SNWc0UnpVd2REVm45KzI1YlhhUk1sT2U0ZlJpQmdVMEZCaVFvUFFPUmdaOFB6NFh1NjYxcTd6MHRLagpYWHB5NDNOM1dETXd4QkxJbVdBRmJUN3I1TVdYN3lBQ2lWTjF2WUtRV2dQcU5BT1BBSmQxdXJWelpoS01tNVRBCjh5a3h5bVZNaDFkVjh0OGFXZUFENE1hSnFxVW9kS2JVUlNzZ1RxQmthQ2VTZTdPN0o0bDNCY1cvZHVaTU1RMksKVWVkMnd5S1docmJQenQ5eFhqZGFpUDQ2NmJWZmliTXNkOGdFeXdJREFRQUJBb0lCQUU1WXJjTi8xVWtTTmJteAp4UjFXNEF4SXArSWQrV0Jnb0lvSXNlNkx0M1ZXaXE0Y09NTXEraGhsOFBra1BUbnRiLzJOdm53ZzczVXp3azNRCjhFTU5CWFQxK0tZUVRXcEoyd1ZUUjFJZm92Y0YzSFFLZzlRa3VBR3Iva0VqemNGa3oxYUpFaStnaFNRNmI3bEIKU01qVlZVMlp2SmdvcFdzcHcrTGc4bitMZ3R4ZG51SW5GMW1BSi8vbEZrTzhHYkF2TUg0cHc4aVVFNlRreGxmUQpVUTFhZlFLNTBrT3V0cVlGdlhzd2t5Mnd4Mk9IUlorc3k1VXhmVmFJMU5LdnU3R0xMRnR0VUFyeW9iSS91a1lzCkFsS1dDR0FBQ2NOOExuUjVVMnNJQ0cyaWRVSjNMNEZ3NERJMGp2NkphRFZPVXB6ZDU1QWR4ZFU0ekxwVGcySUkKVjVCaWF4RUNnWUVBOElpMDZEaVE0U29wZlplajlwMlA4S09UTWQzYVlUTkNaZDEwdFA3azM1TVhscVhSc1E4aQphUHFDT1ZTdEcwRUR3M21xVG5oMThadkZTUGlEVzVCejFRckFNU3pXS01ickswU293THZKSDU0Sk16YURZMVJ2ClhvbzRxdFJwb2d6WForMmt1dTVoMm9zbDE0M09qVjNxOGVlaG5lSDR4bFNNZUduZ3o4RDM0ODhDZ1lFQWtzaDUKRUZYL2QyYkVjL010NjJPR05WRElyRzZ0UnNPTmZOS2Z0Q1k0eFdrUlh6MnI5TzFtVzNIN3h4M2YwbzFrYldsYgpQRDEzcFBXTk9BYkZyODk0SGJuR3E1TmVhQmI0dzlBNEc1cnRxanFDbERwVlRSWjJrb1Z4LytCZHUwVnJPYUl6CnBXR3pqL1V6LzNBN2xlanB5NjI0LzVDRW96SUVkZ3EydVFQUUFrVUNnWUVBdDF6L3pDZVRDcE5CbmVTRHNmVGIKVGU3a3Z4Y0k2eUJRZGFjazJQV1hOSGpGZXFwZCtFUTVUeDNwT0JzOCs1SE1kSy9EREo3NENuOWRIZ3VVMTdCLwpIT0ZkTWgra0F1SGhWTks2Y25LMUY4MDU1amlnWUpCMWRmU1l6bUd2UlVIVTAvMXRuck1yRlpjTitneTRjVHd2ClpzblZncTVKSDZoRWpXYnBZbmNRZ2pFQ2dZQUVxM1lXaS9YZHNacE1hZzhxN3ZhbEdaWFl6b2lhdUx2Mm5halIKRFdvKzlaSEU2dXhlbFhMdE05b2p3cEtOVzB3M291TnhMaTl4UXhLa0Zxc1JaZE5YZHNLWVVNN3ZGdFFCUHMyYQpLenFtY01nWXVTWmZsbmhkUHZ1YWZXUGVBbDVmN2dZZ205UWZuMWh4SnZ2dVVBT29KRFcvZzdTRWtLSE5zNWVPCm1VMXoxUUtCZ0g1NGFab1MzOWJJeGtJNWxvV2FpMUlOSkh6WWRlM0FPaHpuWEY4MllRUHczdCtmbTE4QWZYV04KVTdMNFQ2QjFYbThqVVpuV0ZJTVBjTjhENUNBQVFKZkNuTlhlMFNkTkhLc0VVaUU5blh1dzBnT2JkNjJsR0hXMAp0QUpkSjc4QU53cTk3SDZ5T2llRTFQZktkTS9tKzM2SktvbGxTcStTbXVaTFNhbEk1Qkw3Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: swj-gke-tls
  namespace: api-swj
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHYmpDQ0JGYWdBd0lCQWdJUkFKMmQ5bEQwdTFHRk5nNkMwbkNmcDIwd0RRWUpLb1pJaHZjTkFRRU1CUUF3DQpTekVMTUFrR0ExVUVCaE1DUVZReEVEQU9CZ05WQkFvVEIxcGxjbTlUVTB3eEtqQW9CZ05WQkFNVElWcGxjbTlUDQpVMHdnVWxOQklFUnZiV0ZwYmlCVFpXTjFjbVVnVTJsMFpTQkRRVEFlRncweU1qQTJNREl3TURBd01EQmFGdzB5DQpNakE0TXpFeU16VTVOVGxhTUJzeEdUQVhCZ05WQkFNVEVHZHJaUzVuZEhSbGMzUXhNeTVqYjIwd2dnRWlNQTBHDQpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ0RyVTAzamJJN0VzZ0pxM3RWenBrOG5Cd3hYbTViDQpFVHNmS1kxNmZReUovc0xJNldZQWo4RWluVlFVRWorOU1tbEJ0cmNpa1RiMFdYcXh0NUxIRjdSN0wzaklUUU54DQo0T2l0Mzk2dC9HNWlqcGE2dFpZSCtCUmtKdnQrMG9wcEtmYlgyV3ZTTjA3b2gvaUlSWXFZMGtJOWU1Um11QnhqDQpCMmFMbXdvRU9BdE9VNHhkNmpJZTJiNFhNdUNqZm80SCtjcWJlSXRTdDVVTkdyLy82T0gyNlk0S3BlOVNIY0RSDQpvVjJGTFRQU25TZUZZeE9hTnliL0JKK1JYeDlPZ3RnSUVmK3lTK3A4WFFJSE1ITWRvdjVWcndORktXc3owbGI3DQo1bUtqTmFvQ0pjTFBSSWJ0RkRIMFZPdS9hTVZUUmwzT3BsbSswOTRxaklYek9scjZ6NTlqNStkM0FnTUJBQUdqDQpnZ0o3TUlJQ2R6QWZCZ05WSFNNRUdEQVdnQlRJMlhob290a1phTlU5Y3Q1ZkNqN2N0WWFHcGpBZEJnTlZIUTRFDQpGZ1FVSjJlTTlrbEtaaVFTQmRVQ0J1cjI4SUZNSGNvd0RnWURWUjBQQVFIL0JBUURBZ1dnTUF3R0ExVWRFd0VCDQovd1FDTUFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNRWtHQTFVZElBUkNNRUF3DQpOQVlMS3dZQkJBR3lNUUVDQWs0d0pUQWpCZ2dyQmdFRkJRY0NBUllYYUhSMGNITTZMeTl6WldOMGFXZHZMbU52DQpiUzlEVUZNd0NBWUdaNEVNQVFJQk1JR0lCZ2dyQmdFRkJRY0JBUVI4TUhvd1N3WUlLd1lCQlFVSE1BS0dQMmgwDQpkSEE2THk5NlpYSnZjM05zTG1OeWRDNXpaV04wYVdkdkxtTnZiUzlhWlhKdlUxTk1VbE5CUkc5dFlXbHVVMlZqDQpkWEpsVTJsMFpVTkJMbU55ZERBckJnZ3JCZ0VGQlFjd0FZWWZhSFIwY0RvdkwzcGxjbTl6YzJ3dWIyTnpjQzV6DQpaV04wYVdkdkxtTnZiVENDQVFNR0Npc0dBUVFCMW5rQ0JBSUVnZlFFZ2ZFQTd3QjFBRWFsVmV0MStwRWdNTFdpDQppV24wODMwUkxFRjB2djFKdUlXcjh2eHcvbTFIQUFBQmdTSnJqaEFBQUFRREFFWXdSQUlnVTN2YUl6dk9TRzdyDQpIMi83L3VNcXV6YURHaVJQTElDMlZ1cUlEMzlTOXdvQ0lDOXN4eVU5QXB0U0o4aTV5Ly9BcTNsOGpyUjhhN0dkDQp3UEQyK2lWanNnVFRBSFlBUWNqS3NkOGlSa29ReHFFNkNVS0hYazR4aXhzRDYrdEx4Mmp3a0dLV0J2WUFBQUdCDQpJbXVOOHdBQUJBTUFSekJGQWlCVzFEREVueDN6eWtvTDFVRkp1b3k3cFRVK29xRjZJRVpiVHQvSXBVT2pTZ0loDQpBS0RzeW1jU1MrbE1zMkVtU2hObHdhcFhSb3VYaDdpYmdoTUNWcXoxU3VBRE1Cc0dBMVVkRVFRVU1CS0NFR2RyDQpaUzVuZEhSbGMzUXhNeTVqYjIwd0RRWUpLb1pJaHZjTkFRRU1CUUFEZ2dJQkFCeDdUdEJYR3NDVTlvZjhUdnV1DQp6WUpCWEwrZ0RCLzQ3ZDlRTUo4WE5RTGtwbk4weXcwYkxuWTBhSk9mbkVSOXdXTnRvUmlnQ2loNkV0empNVVY4DQpzaGtZc01XRGlhRkZLR2crYkF2YWlpaHo4TlBWSDBGc294UXRlcDB1Uk9MWE9MYzA1NG5qd0lTUGI0NmEvRHA3DQpoN0k2RmJlRWQ1d0NwQzBTNjJ0a0NiaUE5YVAxREEzMmhOT3UwTjI4aHZ4aXNRTTFFNllwelcvZ2VaeU54MEFlDQpRUmZjbmFqSDhYV1JLQ1Z4dzVMOENHK0ZpdWxKNmRvNjBWeU9qMHhEb3RwbkNQekROZHpwSGZLUEVlV09EQ0Q2DQpSa0ZsSisxUkhQYlVtc2FoVkEwWTRBdTlheEptRldXN1A5N0NQNFdDdW5jZTFPSGJQbExpMSt3TTZPT3ArbWJMDQpIMFRIaEVaNy8xNzJNcnp5RkxiTXBVTDd2a2xQMEVOS1pXRU5HazRIaC95eXkxa0ZNUHdHaDMzdzRaRnp6Mno5DQp3cS9wVFF0MUI1bTIrTmhSZEtlUEV5M1dkek9hS3NjVFprSDA1L2Fmd0EzTmZCbGplcFFxWVJuWEFCdFZ6Y21ODQpZb2F0bHBnT3U5MlcrbzlnU09hRytnaHdmdG5tYkJSOVAySGs3R1FxSUNBNFEzQTNKaHQwTDBTSzR5NTB3R0JBDQpJTG1rY0MrVHdDL3FPMWhsUjZ0UHpuVS9uY2NKZmpVRDhqZm5NSFBxSWUvb0M3OUdMU2tycUFRR244MDY4Ukt0DQpnTGlZZEs1c2hKZjk3a1R0ME1ScXRHUFhVNVVSdXhORkgrVUh1SjNrei81MVlwSkErVXFjdmlCaTlOQkdzd1lIDQo2QlFvOGRJZTk5RzN0U01VRmZuUU9McHQNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQWc2MU5ONDJ5T3hMSUNhdDdWYzZaUEp3Y01WNXVXeEU3SHltTmVuME1pZjdDeU9sbQ0KQUkvQklwMVVGQkkvdlRKcFFiYTNJcEUyOUZsNnNiZVN4eGUwZXk5NHlFMERjZURvcmQvZXJmeHVZbzZXdXJXVw0KQi9nVVpDYjdmdEtLYVNuMjE5bHIwamRPNklmNGlFV0ttTkpDUFh1VVpyZ2NZd2RtaTVzS0JEZ0xUbE9NWGVveQ0KSHRtK0Z6TGdvMzZPQi9uS20zaUxVcmVWRFJxLy8ramg5dW1PQ3FYdlVoM0EwYUZkaFMwejBwMG5oV01UbWpjbQ0KL3dTZmtWOGZUb0xZQ0JIL3NrdnFmRjBDQnpCekhhTCtWYThEUlNsck05SlcrK1ppb3pXcUFpWEN6MFNHN1JReA0KOUZUcnYyakZVMFpkenFaWnZ0UGVLb3lGOHpwYStzK2ZZK2ZuZHdJREFRQUJBb0lCQUFJUVBpeUhzT3BTRWdacw0KeElNRXVNd0ZXaisvemhUcFFUYnN6TVhGbmVPdnRWZTJxSjJMb3lncXRQMlhoNTRzWXcvZmtDRWZpMi9xMHd4ag0KNXczdHBpdGtCQTJIZjIxU2EvTUZsaFM5NXZEdWNSZzk3anJ6dlVZUWdsSnJkRFhQclltV1k2VW9ycmpnSUpucQ0KRlJEdUFwRzZGUXBEQ2xiVzc5bHlOWWI1WmR2MVYxNzZsblpmejBYdTVrVHEvUmtmaWV5TStsc0lzNHYySmdnaA0KbUlneFZBRWtpVVp6VzYzNktxWnVTSFl0NTd6amR6NDErTTdsVlhmNWZxL2QwR24waVRVZFVWWi8yNm43MHdiUg0KOE5MS2FoY0hFSEVZRmROd3FMcTJ4TGxBS1VpNDJMUjNnclVTNFl3WnVnOTN0Nm1KZm5jb0RuOU1yNE44OWI4OA0KVkU1NlI4a0NnWUVBMnNVNWIwRlRBbUVZWVIvYWxJTGhYNG5PT0NscEN3OVZpcVRqVy9wT01UdWozN0diMFlnQw0KRmpPQXVDR3A3aDhyNlZBZU5Vd0pvMzhQRHlOOGNQdi9IMkE1WHpBY1VPUWt3RStlRkNVZlRKU0E2b0trWFFMUw0KZmwxb2lUUWJzVkI3ajl5bVF1cVJiVzRFNlpPRTdUM3ErWUp2NlBtYVBQUnlJVjJXb1BONmRyTUNnWUVBbWhYVg0KaXduVUdFRW5LUkFxRStvajMzU21YQ0hRZzFoVXlobU9kTmNBaEZNOFNUWXBLWWg1K3lTU2xmK2d2SkVLQTd1MQ0KK3JTd25JWTdkVWdRalg0QW81WDkvY0lid21BK2pBSGdISnZ2OWlUSGkxOEoyaTlNTHpXNVU2YXU4NXlxTXMrUQ0KeWNCVTZZSXR1Z3lXQ001RE9pOU1YUXhDR1JlWFQwQjVxenN2emkwQ2dZQWZQUFk4aXFsZHQ1dVJrc2pWVi9MeQ0KZjJ6dzNBamh5V2kvaVZmbHRGSWgrWkFteXVlaS9iYStrTkFhZXNRVyttQjh5akhtRGx0NSt4U2Rac1hJSkZPRA0KbVd2WHliamhYQkpiVzRNSkFWdjh4Vis3SExoM2g0V2pBWmVCciswY1hvK21OUzJRZElvYmhCQXpnaHNDL1VwbQ0KSWxmMGZsK2x3SW5qZGNlaVorSGV2UUtCZ0FXRUJwTGxsU3dSR1AvRlRseE1JMkNhWW1JbDY3cm43SkVYZlJ2OQ0KbmswZVZhZ2hRalAwYUxsdXc3aU80QWdnQVFYRk1HeDdEMTlyQnJIYUZJMmNGeFhFQnNXUXIwRzBCRWtxd0FVRw0KSi83ZHJpNzFCZnREZWl5dWRhWGk3NXhVM1ZyWVIweVJqL2lUNm1NZ2xEWlllOXVYV2RweTErTGlEMDZNOWs0RQ0KM2w4NUFvR0JBTm55b2MybGRMbzBidTBpMVVwS0NOK0cwdDBlclhKYThlazAyWkxlQUVyYm1CbHVDekZUanlOQQ0KZnVqdlE2Q3RZYWVWRDVlWnBoazhBeHFMbG9PR3FPK3VUSHJSRjNPak84R3hsNkFMandIcEliWEg5T1hLMDdCTQ0KLzQ3ZVpEaUM3eEVSNmNCWUljemR6czJ5Mlh2RWhmdVpVOFlrbXpwNC8xTHNvaEVFYlk3bA0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=
type: kubernetes.io/tls