apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edco-swj-ingress
  namespace: api-swj
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: swj-agile-tls
  rules:
    - host: agile.gttest13.com
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: agile-svc
              port:
                number: 5000
    #- host: edco.gttest13.com
    - http:
        paths:
        - path: /activies/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: activies-svc
              port:
                number: 10001
        - path: /callcenter/
          pathType: Prefix
          backend:
            service:
              name: callcenter-svc
              port:
                number: 10001
        - path: /maintain/
          pathType: Prefix
          backend:
            service:
              name: maintain-svc
              port:
                number: 10001
        - path: /cash/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: cash-svc
              port:
                number: 10001
        - path: /credit/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: credit-svc
              port:
                number: 10001
        - path: /message/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: msg-svc
              port:
                number: 10001
        - path: /product/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: product-svc
              port:
                number: 10001
        - path: /report/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: report-svc
              port:
                number: 10001
        - path: /site/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: site-svc
              port:
                number: 10001
        - path: /statistics/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: statistics-svc
              port:
                number: 10001
        - path: /system/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: system-svc
              port:
                number: 10001
        - path: /user/([a-z]{2}-[a-z]{2}/|swagger/?)
          pathType: Prefix
          backend:
            service:
              name: user-svc
              port:
                number: 10001
        - path: /
          pathType: Prefix
          backend:
            service:
              name: edco-swj-svc
              port:
                number: 8080


---
apiVersion: v1
kind: Secret
metadata:
  name: swj-agile-tls
  namespace: api-swj
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHY2pDQ0JGcWdBd0lCQWdJUVowMm5CbGhnVVVJcmR5U1lqSGt2UFRBTkJna3Foa2lHOXcwQkFRd0ZBREJMDQpNUXN3Q1FZRFZRUUdFd0pCVkRFUU1BNEdBMVVFQ2hNSFdtVnliMU5UVERFcU1DZ0dBMVVFQXhNaFdtVnliMU5UDQpUQ0JTVTBFZ1JHOXRZV2x1SUZObFkzVnlaU0JUYVhSbElFTkJNQjRYRFRJeU1EWXdNVEF3TURBd01Gb1hEVEl5DQpNRGd6TURJek5UazFPVm93SFRFYk1Ca0dBMVVFQXhNU1lXZHBiR1V1WjNSMFpYTjBNVE11WTI5dE1JSUJJakFODQpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFpZXBUdWJ5SlQwZGhVeUVtRXZwcGpxaHduNUZLDQpROTRzN3ZnbHJSeTNCZ1lHRGpaZWVYVit1VDZSb1k2a1UvWnhDWkhmRnZubnBVR3hDM3BlYzNrNi8xbUdiZkZkDQpLWmlKVEQ2K0gwUURTcFd0VG5NM1h4bnNtUjVnNFJ6VXdkRFZuOSsyNWJYYVJNbE9lNGZSaUJnVTBGQmlRb1BRDQpPUmdaOFB6NFh1NjYxcTd6MHRLalhYcHk0M04zV0RNd3hCTEltV0FGYlQ3cjVNV1g3eUFDaVZOMXZZS1FXZ1BxDQpOQU9QQUpkMXVyVnpaaEtNbTVUQTh5a3h5bVZNaDFkVjh0OGFXZUFENE1hSnFxVW9kS2JVUlNzZ1RxQmthQ2VTDQplN083SjRsM0JjVy9kdVpNTVEyS1VlZDJ3eUtXaHJiUHp0OXhYamRhaVA0NjZiVmZpYk1zZDhnRXl3SURBUUFCDQpvNElDZmpDQ0Fub3dId1lEVlIwakJCZ3dGb0FVeU5sNGFLTFpHV2pWUFhMZVh3byszTFdHaHFZd0hRWURWUjBPDQpCQllFRkF2L2xOd3VKNE9PREpjdVd2QXBxOVhiTDlGUE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBTUJnTlZIUk1CDQpBZjhFQWpBQU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakJKQmdOVkhTQUVRakJBDQpNRFFHQ3lzR0FRUUJzakVCQWdKT01DVXdJd1lJS3dZQkJRVUhBZ0VXRjJoMGRIQnpPaTh2YzJWamRHbG5ieTVqDQpiMjB2UTFCVE1BZ0dCbWVCREFFQ0FUQ0JpQVlJS3dZQkJRVUhBUUVFZkRCNk1Fc0dDQ3NHQVFVRkJ6QUNoajlvDQpkSFJ3T2k4dmVtVnliM056YkM1amNuUXVjMlZqZEdsbmJ5NWpiMjB2V21WeWIxTlRURkpUUVVSdmJXRnBibE5sDQpZM1Z5WlZOcGRHVkRRUzVqY25Rd0t3WUlLd1lCQlFVSE1BR0dIMmgwZEhBNkx5OTZaWEp2YzNOc0xtOWpjM0F1DQpjMlZqZEdsbmJ5NWpiMjB3Z2dFRUJnb3JCZ0VFQWRaNUFnUUNCSUgxQklIeUFQQUFkUUJHcFZYcmRmcVJJREMxDQpvb2xwOVBOOUVTeEJkTDc5U2JpRnEvTDhjUDV0UndBQUFZRWVBeHB5QUFBRUF3QkdNRVFDSUIyNWdwdzA2bitQDQpLT3JCK2hFVjZ5bXdBQk1ubllJZzVKN1c1eEFqaGk0MkFpQmw3cHB1L0taclZlNmdsVU5rY0JwY2p4Zm5YMjNTDQp2WWw3WkxrL1JBTm5pZ0IzQUVISXlySGZJa1pLRU1haE9nbENoMTVPTVlzYkErdnJTOGRvOEpCaWxnYjJBQUFCDQpnUjRER2w4QUFBUURBRWd3UmdJaEFPV1ROYi9wSGN2T1V1OVFhRjQxQmpRNkZxV09mSkdwOWxwUlNKYzVXRGc1DQpBaUVBK3BUODR0eEQzSVo3L2dvK0R6Vk5qZGVyZ2RCbXBXQzNJbklBN0xOSDJPMHdIUVlEVlIwUkJCWXdGSUlTDQpZV2RwYkdVdVozUjBaWE4wTVRNdVkyOXRNQTBHQ1NxR1NJYjNEUUVCREFVQUE0SUNBUUI2ZjJNR3dUVTVLMnBnDQp5QlJQbDQ2anFtMkV3UkhQVFR5UUhyZTk5N0l2TmJPTWlWT0tjd3c1NVVBSmo1RFF6OHBLZGhQdXZNdFhTdmd1DQpkeGZnMWtDZmRsbmJHOXJQdlhuOGJmeElJSUg5ZUdxOGQ1UUthLzY0ckNKWW9zeTJpREUrM2ZVNzVZUzBLVC93DQpNZXFkMnIxQnI2dDRBMkxYbWR0Mk85UHVoR2lTYnZGRUg5RzhxanFZWlZBeWVQOER4dHpBRlpYSmVmSUJVb1QvDQp4SldSUVB2SHorczZMN3gvbTVMdm55aUJxeEZYbnNyWXN5N0s0VkNLbkc2K2FnMkcrUDNzOEpTcG14dUQ3M2JLDQpHNnNWaEw2MXR1Z2xSMUd3YnJqVkhpbDBqUFVaNUtnaFRkV2JTTzR3c0d3NUJuNDRXRmt1RVRFNjlpZ2M5VS9jDQp3cUsvN2xSQ2pkWFhxbDZtQXpOL1F4cndONk5XU2JIM3kxd1pobGU1Q1paNWdVVXNLdDU4b3VuRkd2QkdNUThuDQpCK3BtdE8vYytNelN1KzJrME1zdlF0RjZQRklJZ3ZLeXh1WjFzdGZLbmRVcVd6WUpGbmFrQVJMdzVFSVRzVE5WDQpIVDdxSTlxclFYQmpCVS8wcktGRnZPb3NNa00rd1pRWGlOWVpub3A3NnJtSExsZmpTeVhBZEdKUS9uS1NYdUQxDQpQZWk3emFMTitySVhKelY2azdHZmsvRy9Ja2IzVnJDR29ydS9wT2dPT0JZR3RzdW5vdDJlaDlnTHZINEN4dWhwDQo0R0VmVzE1RHBKaWxReXp6ZXF4TTlKVDdhb0t5T2dGRHhJRjNQTFVhQVJKRkp5NnVIZUlNSFJXdURlZ0h2dlNLDQpRd0xOQ25QZUt1QSt3T1o0TzNaU3RialRpWDUyVXc9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQWllcFR1YnlKVDBkaFV5RW1FdnBwanFod241RktROTRzN3ZnbHJSeTNCZ1lHRGpaZQ0KZVhWK3VUNlJvWTZrVS9aeENaSGZGdm5ucFVHeEMzcGVjM2s2LzFtR2JmRmRLWmlKVEQ2K0gwUURTcFd0VG5NMw0KWHhuc21SNWc0UnpVd2REVm45KzI1YlhhUk1sT2U0ZlJpQmdVMEZCaVFvUFFPUmdaOFB6NFh1NjYxcTd6MHRLag0KWFhweTQzTjNXRE13eEJMSW1XQUZiVDdyNU1XWDd5QUNpVk4xdllLUVdnUHFOQU9QQUpkMXVyVnpaaEtNbTVUQQ0KOHlreHltVk1oMWRWOHQ4YVdlQUQ0TWFKcXFVb2RLYlVSU3NnVHFCa2FDZVNlN083SjRsM0JjVy9kdVpNTVEySw0KVWVkMnd5S1docmJQenQ5eFhqZGFpUDQ2NmJWZmliTXNkOGdFeXdJREFRQUJBb0lCQUU1WXJjTi8xVWtTTmJteA0KeFIxVzRBeElwK0lkK1dCZ29Jb0lzZTZMdDNWV2lxNGNPTU1xK2hobDhQa2tQVG50Yi8yTnZud2c3M1V6d2szUQ0KOEVNTkJYVDErS1lRVFdwSjJ3VlRSMUlmb3ZjRjNIUUtnOVFrdUFHci9rRWp6Y0ZrejFhSkVpK2doU1E2YjdsQg0KU01qVlZVMlp2SmdvcFdzcHcrTGc4bitMZ3R4ZG51SW5GMW1BSi8vbEZrTzhHYkF2TUg0cHc4aVVFNlRreGxmUQ0KVVExYWZRSzUwa091dHFZRnZYc3dreTJ3eDJPSFJaK3N5NVV4ZlZhSTFOS3Z1N0dMTEZ0dFVBcnlvYkkvdWtZcw0KQWxLV0NHQUFDY044TG5SNVUyc0lDRzJpZFVKM0w0Rnc0REkwanY2SmFEVk9VcHpkNTVBZHhkVTR6THBUZzJJSQ0KVjVCaWF4RUNnWUVBOElpMDZEaVE0U29wZlplajlwMlA4S09UTWQzYVlUTkNaZDEwdFA3azM1TVhscVhSc1E4aQ0KYVBxQ09WU3RHMEVEdzNtcVRuaDE4WnZGU1BpRFc1QnoxUXJBTVN6V0tNYnJLMFNvd0x2Skg1NEpNemFEWTFSdg0KWG9vNHF0UnBvZ3pYWisya3V1NWgyb3NsMTQzT2pWM3E4ZWVobmVINHhsU01lR25nejhEMzQ4OENnWUVBa3NoNQ0KRUZYL2QyYkVjL010NjJPR05WRElyRzZ0UnNPTmZOS2Z0Q1k0eFdrUlh6MnI5TzFtVzNIN3h4M2YwbzFrYldsYg0KUEQxM3BQV05PQWJGcjg5NEhibkdxNU5lYUJiNHc5QTRHNXJ0cWpxQ2xEcFZUUloya29WeC8rQmR1MFZyT2FJeg0KcFdHemovVXovM0E3bGVqcHk2MjQvNUNFb3pJRWRncTJ1UVBRQWtVQ2dZRUF0MXovekNlVENwTkJuZVNEc2ZUYg0KVGU3a3Z4Y0k2eUJRZGFjazJQV1hOSGpGZXFwZCtFUTVUeDNwT0JzOCs1SE1kSy9EREo3NENuOWRIZ3VVMTdCLw0KSE9GZE1oK2tBdUhoVk5LNmNuSzFGODA1NWppZ1lKQjFkZlNZem1HdlJVSFUwLzF0bnJNckZaY04rZ3k0Y1R3dg0KWnNuVmdxNUpINmhFaldicFluY1FnakVDZ1lBRXEzWVdpL1hkc1pwTWFnOHE3dmFsR1pYWXpvaWF1THYybmFqUg0KRFdvKzlaSEU2dXhlbFhMdE05b2p3cEtOVzB3M291TnhMaTl4UXhLa0Zxc1JaZE5YZHNLWVVNN3ZGdFFCUHMyYQ0KS3pxbWNNZ1l1U1pmbG5oZFB2dWFmV1BlQWw1ZjdnWWdtOVFmbjFoeEp2dnVVQU9vSkRXL2c3U0VrS0hOczVlTw0KbVUxejFRS0JnSDU0YVpvUzM5Ykl4a0k1bG9XYWkxSU5KSHpZZGUzQU9oem5YRjgyWVFQdzN0K2ZtMThBZlhXTg0KVTdMNFQ2QjFYbThqVVpuV0ZJTVBjTjhENUNBQVFKZkNuTlhlMFNkTkhLc0VVaUU5blh1dzBnT2JkNjJsR0hXMA0KdEFKZEo3OEFOd3E5N0g2eU9pZUUxUGZLZE0vbSszNkpLb2xsU3ErU211WkxTYWxJNUJMNw0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=
type: kubernetes.io/tls