apiVersion: v1
kind: Secret
metadata:
  name: sg-app-bucket-secret
  namespace: api-swj
data:
  config_json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicmQtdGVzdC02NDQzNSIsCiAgInByaXZhdGVfa2V5X2lkIjogImE3MjU3NzkxN2M3ODM3ZDRiNGM0NjNjY2I3OGNkZDc5MWZlM2Q5NDgiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2RmMkRuQWVxZUxOS2lcbjdvbXZ0N2JCUGs0SnhuOS9FUWxZZUhuMzVHdlRtdXJIWWpxN09YMUV6K2EybEdGclRyRXlIQlBRU3RkOElzYmhcbkVrNGs2eEtvUmtjL054OXY3bmRlOWwwMmxieU05L2ZoUFkyVk9hUlBvRHdoL1VBcDMxeTN4dUo1OEdqMGxtd3NcblR0NmlsWTdOMVcwaXJwbzAzQnN6K3B1SzRYMGZnOEt1V3M1Nk5aRkZ0WjVsVkRuWjUrT3RtazZFTTF1R0lWY1Jcbmh3NFRmUFNiclJqVUJLbkRaM0NpekNvQ0Nmc2J6TUpJTjZJa0ZieS9XWnVDclNoTHY0YmRvME1UbjRHK0hFN3lcbk5nYUs3UEJ5OHVOWFFFOHhzaU9jRHAwdDlzS3BTbnR4c1F2V3ZmWU1CZFIxUFhPV1cyTGJ1NTRyYkZuN2dkdERcbjdiM05qWitEQWdNQkFBRUNnZ0VBVG5KNnpyVmFxaXlEUWhwMFJDektmNWhNQUh4NVZzNGlqSWw5bnVhTWVwcW9cbkpHV2VBVkZTUHVzYTdJZ2R1Zmc1TkU5ZDR4clVHQVd1Yjc3Ulkzd2ZEK2ZwWnVoSzVWS3U3SUxqek9OcVJnRGdcbjI3VHdCNHJ0ZDZmRks5emJqNytzaS9FcEx6bDYzWkRyRW1xNlk5c0FoUyt3SzEweWUrL0NNUEs3ZE1KNXN5OENcbmVxcE1PU0RURGdFejViTFNMQ0c2cm5QK2xyU1htODhCS1BFZjBycXp2eTNmUW5PRkUwK282WXdLQlRvTnE5dXJcbndCSUIwWkNYZVA2MmpLODhZU3ZuVVRVOXJvM3h2TENSUXhSV2x3RlVCVlRVU21PbU1UTno5ckZueUFKL2Y0TE5cbi80WUFMb09SNE5FTXJkdDN5cHBKbnJtbWVyY3djeWI4aFkxWkxSd1l5UUtCZ1FEVVRmNWQ4UllKbTVFNkFHdmNcbjljdkpocVYybjVjdmkvM0d6UEl3MVVPTW1qenViZ0x0UFp2MVUxWkl2MVR4S2JkbU5jRzVVRHZOa1gwZXB2Q3NcbllrY1k3RElRYkZMR3dYU05CSVZ6TDdjNUZ4QVYwN1NyakE1a2htVVV0NTQxYlZVRWExTmZrbFA3VnBWK1ZLbzJcbkt1d3gvUzFNQmxBVDlsb2hiS2VRZ0U3WTV3S0JnUUM5NmE3OVg4OFd2alY1Ulg0L2hZWHQzMW1RS3lxMmpLbHRcbkRrMUowSXMrK1p0SG4rYTNGTkd1NjNKT292enFWMldkT3B1WjI1YXJhb05ZdDZXcmdTSDRpSStvbnVsSlNsc0hcbkYvQ2lrMks5UmxnUXlNMWtzbmI3Q2V0VHhBM2hUQWlPcHNoVkJDMi9HblVoMGEzbUtCTkFvKzZIc0tzNVNnb2ZcbmxZNUNQTVlsQlFLQmdDTE9CbjF3SUtUQ2xEUm1EVWpVSXV5TzNtRnNHR1Q3RmtlWklidFB1eHM1emZOb3BhSXZcbkQzcFFoenkxNFQ4SUQ4RDUzeUI2UHRPY25sNkFEOFN5OStUbUUrOE5VeVN5WW1FYjlLVEZsY3dPTTl6Z01DWlBcbmQ2eVRPODhCcXpZbkRtRURGMC83dFRqbklPcnRCbHFLL3QzVEc3SHk5djNPelVmZGdEcjRUZlRSQW9HQkFLc21cblREUEFBbXVtbzU1VkNIL0tuM1pPVVBMaVZDNEwraXgwTlNjT3NFN2l1QlFHZ1BBQjdTNU10Y2swamVYTE9hSkdcbnpUQU5lMjJrSWhieituUGpmbS95OGpTdWNlTkJCV1FSS1NYNjJZTm1QN3R3bTluaUUrUU5mbTBSUk1rRHNycU1cbmlBSkdMOHdIMWdQU2FYd0FKY21kY3p3SjlXVTkybjI0VkdwUlJ1alpBb0dBRE9xelRtM1F0MXdYNmtQNXNlMDRcbkZVVlg0L0tYVjk5aUVHRkl1bGFuMVhsSWdvd2hib0xQNXJQQkxIVFRWT1piQUhLQXkxRks4cVBYWnR5NURmZzlcbnRET3JvenRHbWNCZG5lOEtvVHZtNm5iVDJ3OUVnenNINmUzcFd1TUxmZ3FQcVlXcnZ4Q1lWb3RaSE9NNHUrWnhcbkVtdDliS3RRdVFpMUNHSnIwQSthTWYwPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogInNnLWFwcC1idWNrZXRAcmQtdGVzdC02NDQzNS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTYyMzQ2NTI3MTgxOTAyMTgyODUiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3NnLWFwcC1idWNrZXQlNDByZC10ZXN0LTY0NDM1LmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edco-swj-ui
  namespace: api-swj
  labels:
    app.kubernetes.io/name: edco-swj-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0     #更新时候最大无效pod数量
      maxSurge: 1           #更新时候每次最多增加pod数量
  selector:
    matchLabels:
      app.kubernetes.io/name: edco-swj-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edco-swj-ui
    spec:
      volumes:
      - name: config-volume
        secret:
          secretName: sg-app-bucket-secret
          items:
          - key: config_json
            path: sa_credentials.json
      containers:
        - name: gcs-k8s-nginx
          resources:          ##CPU内存限制
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 250m
              memory: 300Mi
          image: gcr.io/rd-test-64435/sg_nginx:v22.2.24.1
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/gcp
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "gcsfuse -o allow_other --implicit-dirs swj-co /etc/nginx/conf.d && ln -s /etc/nginx/conf.d/ui /usr/share/nginx/ui && sleep 5 && nginx -s reload"]
            preStop:
              exec:
                command: ["sh", "-c", "fusermount -u /etc/nginx/conf.d"]
---

apiVersion: v1
kind: Service
metadata:
  name: edco-swj-svc
  namespace: api-swj
  labels:
    app.kubernetes.io/name: edco-swj-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: edco-swj-ui
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-edco-swj
  namespace: api-swj
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edco-swj-ui
  targetCPUUtilizationPercentage: 95
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-edco-swj
  namespace: api-swj
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edco-swj-ui
  updatePolicy:
    updateMode: "Off"