apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-swj-ui
  namespace: api-swj
  labels:
    app.kubernetes.io/name: sg-swj-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0     #更新时候最大无效pod数量
      maxSurge: 1           #更新时候每次最多增加pod数量
  selector:
    matchLabels:
      app.kubernetes.io/name: sg-swj-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sg-swj-ui
    spec:
      volumes:
      - name: config-volume
        secret:
          secretName: sg-app-bucket-secret
          items:
          - key: config_json
            path: sa_credentials.json
      containers:
        - name: gcs-k8s-nginx
          resources:          ##CPU内存限制
            limits:
              cpu: 500m
            requests:
              cpu: 250m
          image: gcr.io/rd-test-64435/sg_nginx:v22.2.24.1
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/gcp
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "gcsfuse -o allow_other --implicit-dirs sg-app-swj /etc/nginx/conf.d & ln -s /etc/nginx/conf.d/ui /usr/share/nginx/ui"]
            preStop:
              exec:
                command: ["sh", "-c", "fusermount -u /etc/nginx/conf.d"]
---

apiVersion: v1
kind: Service
metadata:
  name: sg-swj-svc
  namespace: api-swj
  labels:
    app.kubernetes.io/name: sg-swj-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sg-swj-ui
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sg-swj
  namespace: api-swj
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sg-swj-ui
  targetCPUUtilizationPercentage: 95
---
apiVersion: v1
kind: Secret
metadata:
  name: sg-swj-app-tls
  namespace: api-swj
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdORENDQlJ5Z0F3SUJBZ0lSQU9KT0UvTUxWcEw1VTlSWkhhb2tjdVV3RFFZSktvWklodmNOQVFFTEJRQXcKZ1k4eEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRFZRUUlFeEpIY21WaGRHVnlJRTFoYm1Ob1pYTjBaWEl4RURBTwpCZ05WQkFjVEIxTmhiR1p2Y21ReEdEQVdCZ05WQkFvVEQxTmxZM1JwWjI4Z1RHbHRhWFJsWkRFM01EVUdBMVVFCkF4TXVVMlZqZEdsbmJ5QlNVMEVnUkc5dFlXbHVJRlpoYkdsa1lYUnBiMjRnVTJWamRYSmxJRk5sY25abGNpQkQKUVRBZUZ3MHlNakExTWpVd01EQXdNREJhRncweU16QTJNREV5TXpVNU5UbGFNQjh4SFRBYkJnTlZCQU1URkhOMwphaTFoY0hBdVozUjBaWE4wTVRNdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUE1VnFhdFN5Z1BlY2VMVVFlZE1HZmN6MXlDTDR2L01zTjBGcmRSREJKVGp3RDRmVEtGTzVXeGJ5VzRQUkMKWnRLMCt3SjFpTUczVXg5R256VHVZVFJ2cWxDamVQbTNJUnNxbCt3L0Nra1pjRTBhUDkrSnNLZ1pHWHoybElyQQprU0VaWThjOGY5bFd0NEM2TEdFZmhKcGtDaEZPRGJVKzBHdXkyUEdjcGFPbEM4T1EwLzJ0WWxRZWVFTXlMMXZnCnhVbldRa25aWWM0blU1WHI0YnhIVHZOZmdYRVV0TmJubWkxTWhBZjZDeExxVzU2WGoyRXJ6UXJQTlFzS204eUIKZk1vK0hMZnV3WWt2THlVMFozRFpJRHFZb09XQXIxRkM3RCtIMnF0MFppcmt6WTF2T0x3RG5zb2lheFNreWNjTQpIcXI5U2Y4cm1OMjV1ZGlUS1Qwdm1rRkFwd0lEQVFBQm80SUMrRENDQXZRd0h3WURWUjBqQkJnd0ZvQVVqWXhlCnhGU3RpdUYzNlp2NW13WGh1QUdOWWVFd0hRWURWUjBPQkJZRUZCN2tabjFoYkxmQ3JxVEhnbFhKSE9sSXVQMXkKTUE0R0ExVWREd0VCL3dRRUF3SUZvREFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRgpCd01CQmdnckJnRUZCUWNEQWpCSkJnTlZIU0FFUWpCQU1EUUdDeXNHQVFRQnNqRUJBZ0lITUNVd0l3WUlLd1lCCkJRVUhBZ0VXRjJoMGRIQnpPaTh2YzJWamRHbG5ieTVqYjIwdlExQlRNQWdHQm1lQkRBRUNBVENCaEFZSUt3WUIKQlFVSEFRRUVlREIyTUU4R0NDc0dBUVVGQnpBQ2hrTm9kSFJ3T2k4dlkzSjBMbk5sWTNScFoyOHVZMjl0TDFObApZM1JwWjI5U1UwRkViMjFoYVc1V1lXeHBaR0YwYVc5dVUyVmpkWEpsVTJWeWRtVnlRMEV1WTNKME1DTUdDQ3NHCkFRVUZCekFCaGhkb2RIUndPaTh2YjJOemNDNXpaV04wYVdkdkxtTnZiVENDQVlBR0Npc0dBUVFCMW5rQ0JBSUUKZ2dGd0JJSUJiQUZxQUhjQXJmZSsrbnovRU1pTG5UMmNIajRZYXJSbktWM1BzUXdreW9XR05PdmNnb29BQUFHQQorY3ROT2dBQUJBTUFTREJHQWlFQTBTTk5pZjV1aUFGUjE5TVJnd3BzSzduOExHTWJxSm5EL2l2ZW5keWZTSjhDCklRRFFZS3BjV2YxV0RRZU85RG5WZkFtWWxlSStYVkF4akZoYjR1SXZHMmZQS2dCMkFIb3lqRlRZdHkyMklPbzQKNEZJZTZZUVdjRElUaFUwNzBpdkJPbGVqVXV0U0FBQUJnUG5MVFF3QUFBUURBRWN3UlFJaEFPZ1NRTWtvcFdDKwpHWWkrcE0xUTYvZ2lZdk4yTkhQZnJEZjJLZUV4MUcxeUFpQXBvRnA5T3hEVkR2MDhhZGJ1SUtJdENqbXZUcWpxClo2MzdRdGx1aWdiUWR3QjNBT2crME5vKzlRWTFNdWRYS0x5SmE4a0QwOHZSRVd2czYybmhkMzF0QnIxdUFBQUIKZ1BuTFRONEFBQVFEQUVnd1JnSWhBSXNuNFNVc0tmV2FVZG1Jd0NlTndGbnlOM0xPWVEwRkl3WEllakNZcisvcwpBaUVBeHUyd0lRTkVpelVhVjNDMEpvWlBqdmY1NUxQZDhONGhlU1A0UFFzUTlCY3dId1lEVlIwUkJCZ3dGb0lVCmMzZHFMV0Z3Y0M1bmRIUmxjM1F4TXk1amIyMHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR1p1N01qMU5nTlUKUVlQNGdiUlZ3TnR6NGd0dUl0NmI0eUxNSVBzRkhoUjJzeHY5bGl3Y0hZamlOQml5anBieFk5TkN6c0pScUhETQpKMXZiR3dZMURWMGZMd09udFBhb2VtSzNQa0dSd1dvSzJuU1ZSSTQrS2UwZitWbysyR3E1VmoxRVF3QXlBWENHClBrRzl2V2Vpa1IwNTNyWEQ0Q3l6RjBHdEtkZnJ1WVJLUTc3TjRnVkkyUE0wMTFuRHdZeDNMM0RLQUFGTTE1N0gKelM5aHQzS0Z0amJkZFhXWFNzYXREVW9OU3ZSZEEybStVVmtLWVBTbld6a3ZBT1ZDK2xDSlZTY1ljNHR6OTlVVwp0UnFRWDVvdmJIZXZISzlTRGtYYU1pSmxPTGFxaW9DOFFuQnFrTXJIazVZWHJBTis3V1ZSNHRUMDVtY2l4Q0JnCmhZZnlJM2pBM2NnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRGxXcHExTEtBOTV4NHQKUkI1MHdaOXpQWElJdmkvOHl3M1FXdDFFTUVsT1BBUGg5TW9VN2xiRnZKYmc5RUptMHJUN0FuV0l3YmRUSDBhZgpOTzVoTkcrcVVLTjQrYmNoR3lxWDdEOEtTUmx3VFJvLzM0bXdxQmtaZlBhVWlzQ1JJUmxqeHp4LzJWYTNnTG9zCllSK0VtbVFLRVU0TnRUN1FhN0xZOFp5bG82VUx3NURUL2ExaVZCNTRRekl2VytERlNkWkNTZGxoemlkVGxldmgKdkVkTzgxK0JjUlMwMXVlYUxVeUVCL29MRXVwYm5wZVBZU3ZOQ3M4MUN3cWJ6SUY4eWo0Y3QrN0JpUzh2SlRSbgpjTmtnT3BpZzVZQ3ZVVUxzUDRmYXEzUm1LdVROalc4NHZBT2V5aUpyRktUSnh3d2VxdjFKL3l1WTNibTUySk1wClBTK2FRVUNuQWdNQkFBRUNnZ0VBVVBQMS8xVE5Db3gxSGswWTR1VWt2cXhGZjhpQmI1ek1OMnFiQnVKMFBXVDUKaWR1NUtFSW41b3QyUmRoeFI1Ry94NGxLcXdhVkNvWFRpNFpIVFpBUWlmRUVna0xCM0xHV0N5R2I3cWwyalNqcAp4dm5EdzlMUmFTbXVieWU2YUg5aVV0R1VEUnhOZTErNFZzbkJNakM4ZHNFODU2RzlsaHN0ZVYxdWlSaUZ2T3lUCk03THM3WlR4NDBxR0N6UzI1b0FhTjlRa3pqbUJlenZSUEkwV05qTDNGVE5iT2tWcjhoK0dPdDYvNngvL2R5VGMKak9zUUNYUElVSy9jc3R4SVlBMC9BOW05cWZFalFrQkt5VFhKV2x2SjBrREMwajdNVHIvd0l2Z2NJWGZNNWNVdQpMSlNlQTh1QmpDWVNuM3BYV3ZJZjJwazFCaFJNcFNvOG9ld1JmVXBiZ1FLQmdRRDFyVVRyUDlaR3dZeWtqN3lwCk5FYzlweFZjdC8wOVF2ZFRyYWRhWGxMdzZEUDBRS05wQnkyamhhck1jVjJrMFVRNDVuTjBBdjJxUmsyNnJhVTgKZG4wcEI2anhCU1Y0WnRVR2xwR2FaTXkrVFRudGhsRTlXTjJtNUhVQy9MeUhtSWYyOUpCWmM0ZFBTclU0SXhPbgpUanVjQlRVWHkydzBFZVpiRFRoa1pJeENNUUtCZ1FEdS9jQWs0K3V0TnRHNEEwaEFoR2VtdW5ua1JJemd6Z2JMCm8yNzZ6YnNSSmM1UjdWckhrNS9SRXRsY3hONjR4MW1xTklKRkNxOGsrTDMxL2hReTN3U0p0eWlQcFV1SDBqdnYKNmI2QXU5Q2Nyd0tYM1JBbXR3OHk5U1hEbVhaWnNVMVJIVHAzTmxyNjRmV2paS1NJWkNQVUMvdHdvOFhkdTRaYworNUFSQVVCaVZ3S0JnSFB0Z0NEMkxabVR5VmI1MEkrVGNLNkNBazJQTUh0UTl6NVFLakUxWXpQMGpsZUtqTkdKCnBwcUwvNDJiVFJIeUFaeEwrbHphOEhJQjNMbmpLSjZBVncwZVpUVGVOZEU3elBmZjR2TVU3NXc0K3NXL1pPUnEKNDZUV0Z2VUM1NytnVlVCT0pUTmdsWS92ODlWNmo5S1owdjBMWkFOSFpWYW92NmRsZEovQzVvQnhBb0dBY3pzWQpIUEZrSGdWVGd3VGFIbmw0dkpRbTEyQVNDUVp0a2x3LzAxL0V0WlRqOE82Zm1hRGRLdUtLdVVjWEdFTE9RZG5GCmdlS1A1aVNrK3VuQjlYRkFiK0pIQlZPdW9sTkVvUDJ6NDhBcTZwRWJqL3Qvb1JzY2tmWlBlZ3NSWEZlM3JzZUgKL0JqU0x5c3AwOWxmMTM5cEl3R1AvNVNIZjh5K0VURWVHb1RlOVVzQ2dZQVZQc0VQYTlMN0ZKTXdBa09PM1FFZQpzeXZ2U3N0a0hsSmpGRVgvSTNoaUZrcDN0OVFqeXJBOUp4dGVBa1JkeU1laVN4SElaQkJzMnhxU05hNkRPWm1SCkZuaEpPdHh6cVJCQzRBeVhHdEtRa05tYUdVUFpnai9WcHJ4dkJvNGRKUVNHeXpGeWZzbFd4VmlSRmE2c2ZUaWoKV3o2RVFJWDRWanJDY1RDZEk4bm5Jdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sg-swj-ingress
  namespace: api-swj
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: sg-swj-app-tls
  rules:
  - host: swj-app.gttest13.com
    http:
      paths:
      - path: /user/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 10001
      - path: /message/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: msg-svc
            port:
              number: 10001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sg-swj-svc
            port:
              number: 8080
  - host: swj.gttest13.com
    http:
      paths:
      - path: /user/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 10001
      - path: /message/([a-z]{2}-[a-z]{2}/|swagger/?)
        pathType: Prefix
        backend:
          service:
            name: msg-svc
            port:
              number: 10001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sg-swj-svc
            port:
              number: 8080