apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-config
  namespace: edapi
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-config
  namespace: kube-system
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800