apiVersion: v1 
kind: Namespace   #创建独立的命名空间
metadata:
  name: cloudsql-ed   
--- 
apiVersion: v1
kind: Endpoints
metadata:
  name: ed-cloudsql-svc
  namespace: cloudsql-ed
subsets:
  - addresses:
      - ip: 34.87.46.208
    ports:
      - port: 1433
--- 
apiVersion: v1
kind: Service
metadata:
  name: ed-cloudsql-svc
  namespace: cloudsql-ed
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
